import 'dart:typed_data';
import 'package:flutter/foundation.dart' show kIsWeb;
import 'package:flutter/material.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:intl/intl.dart';
import 'download_helper.dart';

// Import the platform file saver with conditional exports
import 'platform_file_saver_export.dart';

class PdfUtils {
  /// Generate and download a PDF report
  static Future<void> generateAndDownloadReport({
    required String title,
    required String content,
    required String fileName,
    required BuildContext context,
  }) async {
    try {
      // Create PDF document
      final pdf = pw.Document();
      
      // Add pages to PDF
      pdf.addPage(
        pw.MultiPage(
          pageFormat: PdfPageFormat.a4,
          margin: const pw.EdgeInsets.all(32),
          header: (context) {
            return pw.Header(
              level: 0,
              child: pw.Text(
                title,
                style: pw.TextStyle(
                  fontSize: 24,
                  fontWeight: pw.FontWeight.bold,
                ),
              ),
            );
          },
          footer: (context) {
            return pw.Row(
              mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
              children: [
                pw.Text(
                  'Generated on ${DateFormat('dd/MM/yyyy HH:mm').format(DateTime.now())}',
                  style: const pw.TextStyle(fontSize: 10),
                ),
                pw.Text(
                  'Page ${context.pageNumber} of ${context.pagesCount}',
                  style: const pw.TextStyle(fontSize: 10),
                ),
              ],
            );
          },
          build: (context) {
            return [
              pw.SizedBox(height: 20),
              pw.Paragraph(
                text: content,
                style: const pw.TextStyle(
                  fontSize: 12,
                  lineSpacing: 2,
                ),
              ),
              pw.SizedBox(height: 20),
              pw.Divider(),
              pw.SizedBox(height: 10),
              pw.Text(
                'This report was automatically generated by ProTrack',
                style: const pw.TextStyle(
                  fontSize: 10,
                  fontStyle: pw.FontStyle.italic,
                ),
              ),
            ];
          },
        ),
      );

      // Generate timestamp for unique filename
      final timestamp = DateFormat('yyyyMMdd_HHmmss').format(DateTime.now());
      final fileNameWithTimestamp = '${fileName}_$timestamp.pdf';

      // Generate PDF bytes
      final Uint8List pdfBytes = await pdf.save();
      
      if (kIsWeb) {
        // Web platform implementation - use browser download
        WebDownloadHelper.downloadPdfInBrowser(pdfBytes, fileNameWithTimestamp);
      } else {
        // Native platform implementation
        await PlatformFileSaver.saveFile(pdfBytes, fileNameWithTimestamp);
      }
      
      return;
    } catch (e) {
      rethrow;
    }
  }
}
